"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-09 20:50:42.302907

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Native enum types the tables below create. Kept in one list so upgrade and
# downgrade cannot disagree about which types exist.
ENUM_TYPES = (
    "provider",
    "trigger_source",
    "review_run_status",
    "diff_side",
    "finding_category",
    "finding_severity",
    "comment_kind",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('provider', sa.Enum('github', 'gitlab', name='provider'), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('auto_review_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_repositories_provider_id')
    )
    op.create_table('merge_requests',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('source_branch', sa.String(length=255), nullable=False),
    sa.Column('target_branch', sa.String(length=255), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'number', name='uq_merge_requests_repo_number')
    )
    op.create_index(op.f('ix_merge_requests_repository_id'), 'merge_requests', ['repository_id'], unique=False)
    op.create_table('review_runs',
    sa.Column('merge_request_id', sa.Uuid(), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('queued', 'building_context', 'analysing', 'publishing', 'completed', 'failed', 'cancelled', name='review_run_status'), nullable=False),
    sa.Column('trigger', sa.Enum('webhook', 'manual', 'mention', name='trigger_source'), nullable=False),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('tokens_used', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('rejected_findings', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merge_request_id'], ['merge_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_runs_merge_request_id'), 'review_runs', ['merge_request_id'], unique=False)
    op.create_index('uq_review_runs_one_active_per_commit', 'review_runs', ['merge_request_id', 'head_sha'], unique=True, postgresql_where=sa.text("status NOT IN ('cancelled', 'completed', 'failed')"))
    op.create_table('context_payloads',
    sa.Column('review_run_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('tiers', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('file_paths', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_run_id', 'chunk_index', name='uq_context_payloads_chunk')
    )
    op.create_index('ix_context_payloads_digest', 'context_payloads', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_context_payloads_review_run_id'), 'context_payloads', ['review_run_id'], unique=False)
    op.create_table('findings',
    sa.Column('review_run_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('side', sa.Enum('old', 'new', name='diff_side'), nullable=False),
    sa.Column('old_line', sa.Integer(), nullable=True),
    sa.Column('new_line', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('security', 'correctness', 'performance', 'readability', name='finding_category'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='finding_severity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_run_id', 'file_path', 'side', 'old_line', 'new_line', 'category',
                        name='uq_findings_anchor', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_findings_review_run_id'), 'findings', ['review_run_id'], unique=False)
    op.create_table('published_comments',
    sa.Column('review_run_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=True),
    sa.Column('provider_comment_id', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('summary', 'inline', name='comment_kind'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_run_id', 'finding_id', name='uq_published_comments_finding',
                        postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_published_comments_review_run_id'), 'published_comments', ['review_run_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema.

    Autogenerate drops the tables but leaves the native enum types behind,
    which breaks reversibility: `downgrade base` would leave seven orphaned
    types, and the next `upgrade head` would fail trying to create them again.
    They are dropped explicitly below.
    """
    op.drop_index(op.f('ix_published_comments_review_run_id'), table_name='published_comments')
    op.drop_table('published_comments')
    op.drop_index(op.f('ix_findings_review_run_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_context_payloads_review_run_id'), table_name='context_payloads')
    op.drop_index('ix_context_payloads_digest', table_name='context_payloads')
    op.drop_table('context_payloads')
    op.drop_index('uq_review_runs_one_active_per_commit', table_name='review_runs', postgresql_where=sa.text("status NOT IN ('cancelled', 'completed', 'failed')"))
    op.drop_index(op.f('ix_review_runs_merge_request_id'), table_name='review_runs')
    op.drop_table('review_runs')
    op.drop_index(op.f('ix_merge_requests_repository_id'), table_name='merge_requests')
    op.drop_table('merge_requests')
    op.drop_table('repositories')
    # ### end Alembic commands ###

    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
